model:
  num_cells: 256
  lr: 3e-4
  max_grad_norm: 1.0

  gamma: 0.99
  tau: 0.05

  alpha: 0.2
  alpha_lr: 3e-4
  alpha_min: 0.1

  batch_size: 512
  replay_size: 1_000_000

  update_every: 32

  load_initial: true

  use_noisy: false
  noise_sigma: 0.5

  per_alpha: 0.6
  per_beta: 0.4

  #* exploration - IGNORE IF NOISY NETS ARE USED!!!!!
  explore_start: 1
  explore_end: 0.03
  explore_steps: 500_000
