train:
  total_steps: 10_000_000
  log_interval: 1000 # how often (in steps) to print/log training stats
  save_interval: 250_000 # how often (in steps) to save model checkpoints

  seed: 6741
  device: null # null = auto-select (GPU if available, else CPU) use gpu:id or cpu to force

  # pretrained_model: "sac_checkpoint_9904128.pt"
  vae_checkpoint_path: null
  encoder_checkpoint_path: "loss=0.1031.ckpt" #* IMPORTANT: Path to pretrained encoder to load for VAE training

  wandb:
    enabled: true
    project: "AssetoCorsaRL-AssettoCorsa"
    entity: null
    name: null

  checkpoint_dir: "models"
